# Site settings
title: Ceijae James Marchese
email: ceijaemarchese@gmail.com
url: CMarch0
description: "Portfolio of cybersecurity work samples for a junior-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Cybersecurity - Analyst - Ethical Hacker"
meta_author: Marchese Ceijae

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 021B27 #80B3FF
  primary-rgb: "2,27,39" #"128,179,255"
  secondary: 01151E #FD6E8A
  text: F4FDFF
  secondary-dark: 01151E #A2122F
  link1: 200473A
  extra-elements: 2D7B82
  footer: 0A0A0A
# Footer settings
footer:
  copyright: Ceijae James Marchese
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ceijae-marchese-8212771b0/
  - title: github
    url: https://github.com/CMarch0

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:ceijaemarchese@gmail.com

# Postal address (add as many lines as necessary)
location:
  - line: Mesa, Arizona

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.
Cyber icons created by <a href="https://www.flaticon.com/free-icons/cyber-attack" title="cyber attack icons">Freepik - Flaticon</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
